[package]
name = "gormanos"
version = "0.1.0"
authors = ["Will Gorman <wgorman@cerner.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.6.0"
